const products = [
    {
      id: 1,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph1.jpg',
    },
    {
      id: 2,
      name: 'سماعات',
      type:2 ,
      imageSrc: 'public/productImg/ph2.jpg',
    },
    {
      id: 3,
      name: 'سماعات',
      type:2,
      imageSrc: '/public/productImg/ph3.jpg',
    },
    {
      id: 4,
      name: 'سماعات',
      type:2,
      imageSrc: '../../public/productImg/ph4.jpg',
    },
    {
      id: 5,
      name: 'سماعات',
      type:2,
      imageSrc: '/public/productImg/ph5.jpg'
    },
    {
      id: 6,
      name: 'Basic Tee',
      type:3,
      imageSrc: '/public/productImg/ph6.jpg',
    },
    {
      id: 7,
      name: 'Basic Tee',
      type:3,
      imageSrc: '../../public/productImg/ph7.jpg',
    },
    {
      id: 8,
      name: 'سماعات',
      type:2,
      imageSrc: '/public/productImg/ph8.jpg',
    },
    {
      id: 9,
      name: 'سماعات',
      type:2,
      imageSrc: '/public/productImg/ph9.jpg',
    },
    {
      id: 10,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph10.jpg'
    },
    {
      id: 11,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/ph11.jpg',
    },
    {
      id: 12,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/ph12.jpg',
    },
    {
      id: 13,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/ph13.jpg',
    },
    {
      id: 14,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph14.jpg',
    },
    {
      id: 15,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph15.jpg',
    },
    {
      id: 16,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/ph16.jpg',
    },
    {
      id: 17,
      name: 'سماعات',
      type:2,
      imageSrc: '/public/productImg/ph17.jpg',
    },
    {
      id: 18,
      name: 'راوتر',
      type: 5,
      imageSrc: '/public/productImg/ph18.jpg',
    },
    {
      id: 19,
      name: 'وصلة',
      type:1,
      imageSrc: '/public/productImg/ph19.jpg',
    },
    {
      id: 20,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/ph20.jpg',
    },
    {
      id: 21,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/ph22.jpg',
    },
    {
      id: 22,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/ph23.jpg',
    },
    {
      id: 23,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/ph24.jpg',
    },
    {
      id: 24,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/ph25.jpg',
    },
    {
      id: 25,
      name: 'شواحن',
      type:3,
      imageSrc: '/public/productImg/ph26.jpg',
    },
    {
      id: 26,
      name: 'ذاكرة',
      type:9,
      imageSrc: '/public/productImg/ph27.jpg',
    },
    {
      id: 27,
      name: 'ذاكرة',
      type:9,
      imageSrc: '/public/productImg/ph28.jpg',
    },
    {
      id: 28,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph29.jpg',
    },
    {
      id: 29,
      name: 'كرت ذاكرة',
      type:10,
      imageSrc: '/public/productImg/ph30.jpg',
    },
    {
      id: 30,
      name: 'كرت ذاكرة',
      type:1,
      imageSrc: '/public/productImg/ph31.jpg',
    },
    {
      id: 31,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph32.jpg',
    },
    {
      id: 32,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph33.jpg',
    },
    {
      id: 33,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph34.jpg',
    },
    {
      id: 34,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph35.jpg',
    },
    {
      id: 35,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph36.jpg',
    },
    {
      id: 36,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph37.jpg',
    },
    {
      id: 37,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph38.jpg',
    },
    {
      id: 38,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph39.jpg',
    },
    {
      id: 39,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/ph40.jpg',
    },
    {
      id: 39,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/41.jpg',
    },
    {
      id: 40,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/41.jpg',
    },
    {
      id: 41,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/42.jpg',
    },
    {
      id: 42,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/43.jpg',
    },
    {
      id: 43,
      name: 'وصلات',
      type:1,
      imageSrc: '/public/productImg/44.jpg',
    },
    {
      id: 44,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/45.jpg',
    },
    {
      id: 45,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/46.jpg',
    },
    {
      id: 46,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/47.jpg',
    },
    {
      id: 47,
      name: 'بفلات',
      type:6,
      imageSrc: '/public/productImg/48.jpg',
    },
    {
      id: 48,
      name: 'شواحن',
      type:6,
      imageSrc: '/public/productImg/49.jpg',
    },
    {
      id: 49,
      name: 'بفلات',
      type:6,
      imageSrc: '/public/productImg/50.jpg',
    },
    {
      id: 50,
      name: 'بفلات',
      type:6,
      imageSrc: '/public/productImg/51.jpg',
    },
    {
      id: 51,
      name: 'بفلات',
      type:6,
      imageSrc: '/public/productImg/52.jpg',
    },
    {
      id:52,
      name: 'بفلات',
      type:6,
      imageSrc: '/public/productImg/53.jpg',
    },
    {
      id: 53,
      name: 'بفلات',
      type:6,
      imageSrc: '/public/productImg/54.jpg',
    },
    {
      id: 54,
      name: 'كفرات',
      type:8,
      imageSrc: '/public/productImg/55.jpg',
    },
    {
      id: 55,
      name: 'كفرات',
      type:8,
      imageSrc: '/public/productImg/56.jpg',
    },
    {
      id: 56,
      name: 'كفرات',
      type:8,
      imageSrc: '/public/productImg/57.jpg',
    },
    {
      id: 57,
      name: 'كفرات',
      type:8,
      imageSrc: '/public/productImg/58.jpg',
    },
    {
      id: 58,
      name: 'لزقات',
      type:7,
      imageSrc: '/public/productImg/59.jpg',
    },
    {
      id: 59,
      name: 'لزقات',
      type:7,
      imageSrc: '/public/productImg/60.jpg',
    },
    {
      id: 60  ,
      name: 'راوتر',
      type:5,
      imageSrc: '/public/productImg/61.jpg',
    },
    {
      id: 61  ,
      name: 'شواحن',
      type:4,
      imageSrc: '/public/productImg/62.jpg',
    },
    {
      id: 62  ,
      name: 'سماعات',
      type:2,
      imageSrc: '/public/productImg/63.jpg',
    },
    // More products...
  ]

  export default products;